a=int(input("enter first value "))
b=int(input("enter second value "))
c=a+b
d=a-b
e=a*b
f=a/b
h=a%b
print ("sum is = ",c)
print ("differece is =",d)
print ("product = ",e)
print ("quotient =",f)
print("reminder =",h)
